approvedGitRepositories:
  - "**"

defaultSemverRangePrefix: ""

enableScripts: true

enableTelemetry: false

injectEnvironmentFiles:
  - .env?

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  zirion:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
