export enum ErrorCode {
  UNKNOWN_SCOPE = 1,
  UNKNOWN_TARGET = 2,
  TARGET_TYPE_BAD_RESOLVER = 3,
  TARGET_NULL = 4,
  TARGET_DUPLICATE = 5,
  REQUEST_SCOPE_CONTEXT_REQUIRED = 6,
  SINGLETONE_SCOPE_WRONG_CONTEXT = 7,
}
