on:
  - push
  - workflow_dispatch
  - pull_request

name: Coverage

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: |
          corepack enable
          yarn install
          yarn coverage
      - uses: codecov/codecov-action@v4
        with:
          flags: unittests
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
